### ISSUE TITLE
[feat] 닉네임 수정 분기처리

### ISSUE THREAD

**Issue by seungchan2** [team-journey/journey-iOS#468]
- [ ] 닉네임 수정 분기처리

**Comment by iamcho2** [comment]
제가 해놨어요 nicknameUsage enum으로

**Comment by iamcho2** [comment]
![image](https://user-images.githubusercontent.com/28949235/138251948-c1bb2991-a8c9-49bb-bfb0-d84735044d1f.png)
이거확인해서서 쓰면댑니당
